### ISSUE TITLE
Most appropiate Sinhala spelling for "Pali Language"?

### ISSUE THREAD

**Issue by tharindusathis** [pathnirvana/tipitaka.lk#11]
පාලි භාෂාව යන්නෙහි අක්ෂර වින්‍යාසය සඳහා වඩාත් උචිත පාළි/පාලි භාෂාව ද? මේ වගේ තැන්වලදි මට හිතෙන විදිහට "පාලි භාෂාව" ලෙස අක්ෂර වින්‍යාසය භාවිත වෙන එක සුදුසුයි. 

https://github.com/pathnirvana/tipitaka.lk/blob/e19c7c3fe35c30be8a7b7a1cda20f8ca803438b2/src/views/Settings.vue#L20-L25
https://github.com/pathnirvana/tipitaka.lk/blob/e19c7c3fe35c30be8a7b7a1cda20f8ca803438b2/src/views/Settings.vue#L50-L51
https://github.com/pathnirvana/tipitaka.lk/blob/e19c7c3fe35c30be8a7b7a1cda20f8ca803438b2/src/views/Settings.vue#L135-L137

එසේ වෙනස් කිරීමට අවශ්‍ය නම් මන් PR එකක් දාන්නම්.

**Comment by pathnirvana** [comment]
I think either one should be fine
I have seen lot of old books use පාළි and we can follow that old standard

**Comment by tharindusathis** [comment]
Yes, thank you for the information. Better to use the old standard.
