### ISSUE TITLE
two issue in mahaniddesa and chula niddesa

### ISSUE THREAD

**Issue by pathnirvana** [pathnirvana/tipitaka.lk#15]
මෙතනට සිංහලෙන් " මානාන්ධකාරය " දාන්න වෙයි...
https://tipitaka.lk/kn-nc-17-10/216-6/pali

![W  L E L _2021-03-03_1](https://user-images.githubusercontent.com/18088975/111578302-79c34400-87e6-11eb-9eef-0d93bb9e9321.jpg)

මෙතන පාලියට " ධාතුලොකෙ " දාන්නවෙයි වගේ...
https://tipitaka.lk/kn-mn-3-4/49-0/pali

පිංතූරය තැන

![W  L E L _2021-03-18_1](https://user-images.githubusercontent.com/18088975/111578343-8ba4e700-87e6-11eb-9407-9e3d7b1f9d8d.jpg)

**Comment by DivineRiver** [comment]
Corrected as mentioned

**Comment by pathnirvana** [comment]
Many merits @DivineRiver
