### ISSUE TITLE
ඛුද්දක නිකාය > පටිසම‍්භිදාමග‍්ගො > 1. මහාවග‍්ගො > ඤාණකථා > 8. ආදීනව ඥානය

### ISSUE THREAD

**Issue by anomajaya** [pathnirvana/tipitaka.lk#29]
නමෝ බුද්ධාය!

මෙහි, https://tipitaka.lk/kn-ps-1-1-9/55-1/sinh "කිසෙයින් උත්පාදාදීන් **භව**වශයෙන් වැටහීමේ ප්‍රඥාව ආදීනවඥාන වෙයි යත්:" (කථං භයතුපට‍්ඨානෙ පඤ‍්ඤා ආදීනවෙ ඤාණං:) යන්නෙහි  "භවවශයෙන්" යන්න "**භය**වශයෙන්" ලෙස නිවැරදි විය යුතුවේ. 

මෙය බුද්ධ ජයන්ති පෙලහි නිවැරදිව දක්වා ඇත.

![Screenshot 2021-09-10 at 21 28 56](https://user-images.githubusercontent.com/2525876/132883119-9ffaa9cd-be0d-444a-92e9-3fa3128534d8.png)

මෙය නිවැරදි කරන මෙන් මෙත් සිතින් ඉල්ලා සිටිමි.

තෙරුවන් සරණයි!!!

**Comment by DivineRiver** [comment]
the correction has been made.

**Comment by pathnirvana** [comment]
Many merits @DivineRiver and @anomajaya
