### ISSUE TITLE
ඛුද්දක නිකාය > පටිසම‍්භිදාමග‍්ගො > 1. මහාවග‍්ගො > ඤාණකථා > 15. වත්‍ථුනානත‍්තඤාණං

### ISSUE THREAD

**Issue by anomajaya** [pathnirvana/tipitaka.lk#34]
නමෝ බුද්ධාය!

මෙහි, [https://tipitaka.lk/kn-ps-1-1-16/71-1/sinh](url) "ආත්මහෙයින් **හෙයින්** නිශ්චය නො කෙරෙයි" යන්න "ආත්මහෙයින් නිශ්චය නො කෙරෙයි" ලෙස නිවැරදි විය යුතුවේ.

![Screenshot 2021-10-21 at 09 18 44](https://user-images.githubusercontent.com/2525876/138209292-ae21fb86-a387-4a2c-9981-e745a4469657.png)

මෙය බුද්ධ ජයන්ති පෙලහි නිවැරදිව දක්වා ඇත.

![Screenshot 2021-10-21 at 09 18 12](https://user-images.githubusercontent.com/2525876/138209398-cf6f67e1-cd62-496d-ae73-c83a15248fdf.png)

මෙය නිවැරදි කරන මෙන් මෙත් සිතින් ඉල්ලා සිටිමි.

තෙරුවන් සරණයි!!!

**Comment by pathnirvana** [comment]
Many merits @anomajaya

**Comment by pathnirvana** [comment]
Many merits @DivineRiver and @anomajaya
