### ISSUE TITLE
missing sentence in mn pali and sinhala

### ISSUE THREAD

**Issue by pathnirvana** [pathnirvana/tipitaka.lk#8]
අැප් එකේ ටිකක්අඩුය මුල්ම චේදය 246පිටුව
අඩු ටිකට මේ එවන පොටෝ එකේ තියෙන  පාලිය හා සිංහල එකතු කරන්න(පැහැදිලව පොටෝ එක පේනව අැතිනේ...පැරණි මුද්‍රණය 3.5GB සොෆ්ට්වෙයා හා pdf වල ද එ් දෝසය අැත...නව මුද්‍රණය හරි...මේ එහි පිංතූරයකි)
https://tipitaka.lk/kn-mn-8-11/122-0/pali
![W  L E L _2021-02-24_1](https://user-images.githubusercontent.com/18088975/108953090-2ead8980-769d-11eb-8d87-9f045c47d588.jpg)

**Comment by tharindusathis** [comment]
Going to work on this issue. Need a little clarification; we have to edit `public/static/text/*.json` directly, is it?

**Comment by pathnirvana** [comment]
@tharindusathis yes you can edit the json files directly
however could you wait a bit as I have asked from a scholar monk to confirm the change

**Comment by tharindusathis** [comment]
Yeah sure. Notify me when its ready

**Comment by Ven-Ariyadassana-Thero** [comment]
Yes, Mr. Janaka, lets correct it. Those words should be added. the phrase should be like this "**චක්‌ඛුභූතො ඤාණභූතො ධම්‌මභූතො බ්‍රහ්‌මභූතො, වත්‌තා පවත්‌තා**"

**Comment by pathnirvana** [comment]
@Ven-Ariyadassana-Thero  Many merits swaminvahansa
@tharindusathis can go ahead with the change

**Comment by tharindusathis** [comment]
Many merits @Ven-Ariyadassana-Thero. I will continue.

**Comment by pathnirvana** [comment]
many merits Bhante
just for future reference putting the link from cst https://tipitaka.app/?a=en8-96-si
